name: Auto Deploy to pilox upload service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Run deploy script
      run: |
        echo "
          cd htdocs/upload.pilox.com.ng
          git pull origin upload
        " > temp_dev.sh
        sshpass -p "${{ secrets.UPLOAD_VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.UPLOAD_VPS_USER }}@${{ secrets.UPLOAD_VPS_HOST }} 'bash -s' < temp_dev.sh