name: Auto Deploy to pilox api

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Run deploy script
      run: |
        echo '#!/bin/bash
          set -e
          if [ ! -d "$HOME/.nvm" ]; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          fi
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 20 || true
          nvm use 20
          cd htdocs/api.pilox.com.ng
          git pull origin main
          npm install
          echo "Deployment completed successfully!"
        ' > temp_dev.sh
        chmod +x temp_dev.sh
        sshpass -p "${{ secrets.API_VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.API_VPS_USER }}@${{ secrets.VPS_HOST }} 'bash -s' < temp_dev.sh